server:
  port: 9090
  contextPath: /Nuevo
  
spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/spring_jpa?useSSL=false
    #username: root
    #password: root-->
    driver-class-name: oracle.jdbc.driver.OracleDriver    
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /
      suffix: .jsp